name: Dependency Review

on:
  pull_request:
    branches: "**"

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Dependency Review
        run: echo "Reviewing dependencies..."
