name: build

on: 
  push:
  workflow_dispatch:
    inputs:
      runMode:
        description: 'Run Mode (test | publish)'
        required: true
        default: 'test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18.x'
      #     registry-url: 'https://npm.pkg.github.com'

      # - name: Install Dependencies
      #   run: yarn install

      # - name: Run Tests
      #   run: yarn test-check
      #   env:
      #     CI: true

      - name: Build
        if: ${{ (github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.runMode == 'publish') }}
        run: echo "Building..."

      - name: Publish
        if: ${{ (github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.runMode == 'publish') }}
        run: echo "Publishing..."
